apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: localhost:32000/prometheus:lab
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            # ADDED THE LINE BELOW TO ENABLE THE RECEIVER
            - "--web.enable-remote-write-receiver"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: alert-rules
              mountPath: /etc/prometheus/alert-rules.yaml
              subPath: alert-rules.yaml
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: alert-rules
          configMap:
            name: prometheus-alert-rules